### ISSUE TITLE
Permission denied to set process priority to high 

### ISSUE THREAD

**Issue by iluvatyr** [nicknsy/jellyscrub#122]
```[23:28:29] [INF] [27] Nick.Plugin.Jellyscrub.Drawing.OldMediaEncoder: Setting generation process priority to High
[23:28:29] [ERR] [27] Nick.Plugin.Jellyscrub.Drawing.OldMediaEncoder: Unable to set process priority: Permission denied (will not prevent BIF generation!)
```

Any idea why this is the case? Everything works, but I saw this in the logs.

**Comment by nicknsy** [comment]
On linux (maybe Windows too) elevation is required to set certain process priorities--I believe above normal. If you're running in docker as a non-root user or outside of docker as the default jellyfin user this is expected. This cam be fixed in docker by setting the PID to 0 or by editing the /etc/security/limits.conf file to allow norma users certain priorities.

Although, generally you wouldn't want BIF generation to take priority over whatever else if happening on your system.
