### ISSUE TITLE
On demand scanning fails for .strm files

### ISSUE THREAD

**Issue by whiteowl3** [nicknsy/jellyscrub#45]
I see that BIFMetadataProvider runs when expected on the target .strm file, but .bif files are never created. bif files are sometimes created for strm files during the scheduled task, but not always.

**Comment by nicknsy** [comment]
BIF files require that the entirety of the media be available so that it can get thumbnails for each part. If you're streaming from an external source I'm not sure if there is any realistic way to run the BIF generation over it on demand. 

You said that bif files are sometimes created during the scheduled task. When they are created do they work properly later when watching the stream?

**Comment by whiteowl3** [comment]
on-demand generation actually *does* eventually result in a .bif file, but I have not checked logs to see how this actually goes down.  if I watch an item with "on-demand" enabled, the bif file will appear many hours later on my rpi4 server.  will close for now.
