### ISSUE TITLE
Provide a way to generate the BIF file on another computer

### ISSUE THREAD

**Issue by Extarys** [nicknsy/jellyscrub#7]
I don't know how how feasable this is, but I've been running this on my Pi 4 for 3 hours and it managed to generate the BIF files for 5 epsiodes of 45 minutes.

It would be lovely to be able to run a command on another, faster, computer to generate the initial files.

**Comment by nicknsy** [comment]
Are your media files stored externally? You could enable the "save locally with media" option and plug it into it into a faster pc, then you could start a jellyfin server with just this plugin and generate all the bif files there. Just make sure you have the local option enabled on both servers.

For me personally, going from my main pc to my jellyfin server computer made generation take about 4-5x as long, but I guess that makes sense since the cpu benchmark score of my main computer is about 3x better.

**Comment by Extarys** [comment]
Oh good idea. I'll spin up a docker container locally and generate them that way!
I already have that option enabled. I like having all the data at the same place when possible :innocent:
