### ISSUE TITLE
Video files less than 30 seconds in length don't generate a BIF file.

### ISSUE THREAD

**Issue by maru801** [nicknsy/jellyscrub#75]
I have some extras for shows that are a mix between 20 seconds to 1 minute in length. I ran into issues when I noticed an extras folder didn't get BIF files generated for all extras, so I then tried to rescan the affected extras, but nothing happened. I then noticed that only the video files that were longer than 30 seconds got a BIF file generated. I double checked this by comparing this with other videos that I have, and I have found all extras under 30 seconds don't get a BIF file.

Is this a design choice since files that short in length don't really need to be scrubbed?

**Comment by nicknsy** [comment]
Yeah looks like in the BIFMetadataProvider there is a minimum length defined. 
```public static long MinRunTimeTicks = TimeSpan.FromSeconds(30).Ticks; ```

This could be made to check if the runtime is less than the set interval instead of a static 30, but a better long term solution would be to have the ability to scale the interval to the runtime since 3 preview images aren't very helpful anyways.
